package com.king.words.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class AuthRelation implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authrelation.authRelId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer authrelid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authrelation.userId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authrelation.authId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer authid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authrelation.state
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authrelation.createDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyyMMddHHmmss")
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authrelation.expireDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyyMMddHHmmss")
    private Date expiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authrelation.authRelId
     *
     * @return the value of authrelation.authRelId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getAuthrelid() {
        return authrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authrelation.authRelId
     *
     * @param authrelid the value for authrelation.authRelId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setAuthrelid(Integer authrelid) {
        this.authrelid = authrelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authrelation.userId
     *
     * @return the value of authrelation.userId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authrelation.userId
     *
     * @param userid the value for authrelation.userId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authrelation.authId
     *
     * @return the value of authrelation.authId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getAuthid() {
        return authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authrelation.authId
     *
     * @param authid the value for authrelation.authId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setAuthid(Integer authid) {
        this.authid = authid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authrelation.state
     *
     * @return the value of authrelation.state
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authrelation.state
     *
     * @param state the value for authrelation.state
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authrelation.createDate
     *
     * @return the value of authrelation.createDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authrelation.createDate
     *
     * @param createdate the value for authrelation.createDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authrelation.expireDate
     *
     * @return the value of authrelation.expireDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Date getExpiredate() {
        return expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authrelation.expireDate
     *
     * @param expiredate the value for authrelation.expireDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setExpiredate(Date expiredate) {
        this.expiredate = expiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", authrelid=").append(authrelid);
        sb.append(", userid=").append(userid);
        sb.append(", authid=").append(authid);
        sb.append(", state=").append(state);
        sb.append(", createdate=").append(createdate);
        sb.append(", expiredate=").append(expiredate);
        sb.append("]");
        return sb.toString();
    }
}