package com.king.words.model;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class RoleInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.roleId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.name
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.description
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.userId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.service
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer service;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.state
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.createDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyyMMddHHmmss")
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column roleinfo.modifyDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyyMMddHHmmss")
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table roleinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.roleId
     *
     * @return the value of roleinfo.roleId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.roleId
     *
     * @param roleid the value for roleinfo.roleId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setRoleid(Integer roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.name
     *
     * @return the value of roleinfo.name
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.name
     *
     * @param name the value for roleinfo.name
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.description
     *
     * @return the value of roleinfo.description
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.description
     *
     * @param description the value for roleinfo.description
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.userId
     *
     * @return the value of roleinfo.userId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.userId
     *
     * @param userid the value for roleinfo.userId
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.service
     *
     * @return the value of roleinfo.service
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.service
     *
     * @param service the value for roleinfo.service
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setService(Integer service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.state
     *
     * @return the value of roleinfo.state
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.state
     *
     * @param state the value for roleinfo.state
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.createDate
     *
     * @return the value of roleinfo.createDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.createDate
     *
     * @param createdate the value for roleinfo.createDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column roleinfo.modifyDate
     *
     * @return the value of roleinfo.modifyDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column roleinfo.modifyDate
     *
     * @param modifydate the value for roleinfo.modifyDate
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roleinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleid=").append(roleid);
        sb.append(", name=").append(name);
        sb.append(", description=").append(description);
        sb.append(", userid=").append(userid);
        sb.append(", service=").append(service);
        sb.append(", state=").append(state);
        sb.append(", createdate=").append(createdate);
        sb.append(", modifydate=").append(modifydate);
        sb.append("]");
        return sb.toString();
    }
}