package com.king.words.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUseridIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(Integer value) {
            addCriterion("userId =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(Integer value) {
            addCriterion("userId >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(Integer value) {
            addCriterion("userId <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<Integer> values) {
            addCriterion("userId in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andOrganizeIsNull() {
            addCriterion("organize is null");
            return (Criteria) this;
        }

        public Criteria andOrganizeIsNotNull() {
            addCriterion("organize is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizeEqualTo(String value) {
            addCriterion("organize =", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeNotEqualTo(String value) {
            addCriterion("organize <>", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeGreaterThan(String value) {
            addCriterion("organize >", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeGreaterThanOrEqualTo(String value) {
            addCriterion("organize >=", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeLessThan(String value) {
            addCriterion("organize <", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeLessThanOrEqualTo(String value) {
            addCriterion("organize <=", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeLike(String value) {
            addCriterion("organize like", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeNotLike(String value) {
            addCriterion("organize not like", value, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeIn(List<String> values) {
            addCriterion("organize in", values, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeNotIn(List<String> values) {
            addCriterion("organize not in", values, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeBetween(String value1, String value2) {
            addCriterion("organize between", value1, value2, "organize");
            return (Criteria) this;
        }

        public Criteria andOrganizeNotBetween(String value1, String value2) {
            addCriterion("organize not between", value1, value2, "organize");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNamepinIsNull() {
            addCriterion("namePin is null");
            return (Criteria) this;
        }

        public Criteria andNamepinIsNotNull() {
            addCriterion("namePin is not null");
            return (Criteria) this;
        }

        public Criteria andNamepinEqualTo(String value) {
            addCriterion("namePin =", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinNotEqualTo(String value) {
            addCriterion("namePin <>", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinGreaterThan(String value) {
            addCriterion("namePin >", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinGreaterThanOrEqualTo(String value) {
            addCriterion("namePin >=", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinLessThan(String value) {
            addCriterion("namePin <", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinLessThanOrEqualTo(String value) {
            addCriterion("namePin <=", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinLike(String value) {
            addCriterion("namePin like", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinNotLike(String value) {
            addCriterion("namePin not like", value, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinIn(List<String> values) {
            addCriterion("namePin in", values, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinNotIn(List<String> values) {
            addCriterion("namePin not in", values, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinBetween(String value1, String value2) {
            addCriterion("namePin between", value1, value2, "namepin");
            return (Criteria) this;
        }

        public Criteria andNamepinNotBetween(String value1, String value2) {
            addCriterion("namePin not between", value1, value2, "namepin");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andZoneqqIsNull() {
            addCriterion("zoneqq is null");
            return (Criteria) this;
        }

        public Criteria andZoneqqIsNotNull() {
            addCriterion("zoneqq is not null");
            return (Criteria) this;
        }

        public Criteria andZoneqqEqualTo(String value) {
            addCriterion("zoneqq =", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqNotEqualTo(String value) {
            addCriterion("zoneqq <>", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqGreaterThan(String value) {
            addCriterion("zoneqq >", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqGreaterThanOrEqualTo(String value) {
            addCriterion("zoneqq >=", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqLessThan(String value) {
            addCriterion("zoneqq <", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqLessThanOrEqualTo(String value) {
            addCriterion("zoneqq <=", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqLike(String value) {
            addCriterion("zoneqq like", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqNotLike(String value) {
            addCriterion("zoneqq not like", value, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqIn(List<String> values) {
            addCriterion("zoneqq in", values, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqNotIn(List<String> values) {
            addCriterion("zoneqq not in", values, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqBetween(String value1, String value2) {
            addCriterion("zoneqq between", value1, value2, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andZoneqqNotBetween(String value1, String value2) {
            addCriterion("zoneqq not between", value1, value2, "zoneqq");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Integer value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Integer value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Integer value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Integer value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Integer value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Integer> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Integer> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Integer value1, Integer value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Integer value1, Integer value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andApplydateIsNull() {
            addCriterion("applyDate is null");
            return (Criteria) this;
        }

        public Criteria andApplydateIsNotNull() {
            addCriterion("applyDate is not null");
            return (Criteria) this;
        }

        public Criteria andApplydateEqualTo(Date value) {
            addCriterion("applyDate =", value, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateNotEqualTo(Date value) {
            addCriterion("applyDate <>", value, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateGreaterThan(Date value) {
            addCriterion("applyDate >", value, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateGreaterThanOrEqualTo(Date value) {
            addCriterion("applyDate >=", value, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateLessThan(Date value) {
            addCriterion("applyDate <", value, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateLessThanOrEqualTo(Date value) {
            addCriterion("applyDate <=", value, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateIn(List<Date> values) {
            addCriterion("applyDate in", values, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateNotIn(List<Date> values) {
            addCriterion("applyDate not in", values, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateBetween(Date value1, Date value2) {
            addCriterion("applyDate between", value1, value2, "applydate");
            return (Criteria) this;
        }

        public Criteria andApplydateNotBetween(Date value1, Date value2) {
            addCriterion("applyDate not between", value1, value2, "applydate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateIsNull() {
            addCriterion("acceptDate is null");
            return (Criteria) this;
        }

        public Criteria andAcceptdateIsNotNull() {
            addCriterion("acceptDate is not null");
            return (Criteria) this;
        }

        public Criteria andAcceptdateEqualTo(Date value) {
            addCriterion("acceptDate =", value, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateNotEqualTo(Date value) {
            addCriterion("acceptDate <>", value, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateGreaterThan(Date value) {
            addCriterion("acceptDate >", value, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateGreaterThanOrEqualTo(Date value) {
            addCriterion("acceptDate >=", value, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateLessThan(Date value) {
            addCriterion("acceptDate <", value, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateLessThanOrEqualTo(Date value) {
            addCriterion("acceptDate <=", value, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateIn(List<Date> values) {
            addCriterion("acceptDate in", values, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateNotIn(List<Date> values) {
            addCriterion("acceptDate not in", values, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateBetween(Date value1, Date value2) {
            addCriterion("acceptDate between", value1, value2, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAcceptdateNotBetween(Date value1, Date value2) {
            addCriterion("acceptDate not between", value1, value2, "acceptdate");
            return (Criteria) this;
        }

        public Criteria andAccepteridIsNull() {
            addCriterion("accepterId is null");
            return (Criteria) this;
        }

        public Criteria andAccepteridIsNotNull() {
            addCriterion("accepterId is not null");
            return (Criteria) this;
        }

        public Criteria andAccepteridEqualTo(Integer value) {
            addCriterion("accepterId =", value, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridNotEqualTo(Integer value) {
            addCriterion("accepterId <>", value, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridGreaterThan(Integer value) {
            addCriterion("accepterId >", value, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridGreaterThanOrEqualTo(Integer value) {
            addCriterion("accepterId >=", value, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridLessThan(Integer value) {
            addCriterion("accepterId <", value, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridLessThanOrEqualTo(Integer value) {
            addCriterion("accepterId <=", value, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridIn(List<Integer> values) {
            addCriterion("accepterId in", values, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridNotIn(List<Integer> values) {
            addCriterion("accepterId not in", values, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridBetween(Integer value1, Integer value2) {
            addCriterion("accepterId between", value1, value2, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepteridNotBetween(Integer value1, Integer value2) {
            addCriterion("accepterId not between", value1, value2, "accepterid");
            return (Criteria) this;
        }

        public Criteria andAccepterIsNull() {
            addCriterion("accepter is null");
            return (Criteria) this;
        }

        public Criteria andAccepterIsNotNull() {
            addCriterion("accepter is not null");
            return (Criteria) this;
        }

        public Criteria andAccepterEqualTo(String value) {
            addCriterion("accepter =", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterNotEqualTo(String value) {
            addCriterion("accepter <>", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterGreaterThan(String value) {
            addCriterion("accepter >", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterGreaterThanOrEqualTo(String value) {
            addCriterion("accepter >=", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterLessThan(String value) {
            addCriterion("accepter <", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterLessThanOrEqualTo(String value) {
            addCriterion("accepter <=", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterLike(String value) {
            addCriterion("accepter like", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterNotLike(String value) {
            addCriterion("accepter not like", value, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterIn(List<String> values) {
            addCriterion("accepter in", values, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterNotIn(List<String> values) {
            addCriterion("accepter not in", values, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterBetween(String value1, String value2) {
            addCriterion("accepter between", value1, value2, "accepter");
            return (Criteria) this;
        }

        public Criteria andAccepterNotBetween(String value1, String value2) {
            addCriterion("accepter not between", value1, value2, "accepter");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNull() {
            addCriterion("birthDate is null");
            return (Criteria) this;
        }

        public Criteria andBirthdateIsNotNull() {
            addCriterion("birthDate is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdateEqualTo(Date value) {
            addCriterion("birthDate =", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotEqualTo(Date value) {
            addCriterion("birthDate <>", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThan(Date value) {
            addCriterion("birthDate >", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateGreaterThanOrEqualTo(Date value) {
            addCriterion("birthDate >=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThan(Date value) {
            addCriterion("birthDate <", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateLessThanOrEqualTo(Date value) {
            addCriterion("birthDate <=", value, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateIn(List<Date> values) {
            addCriterion("birthDate in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotIn(List<Date> values) {
            addCriterion("birthDate not in", values, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateBetween(Date value1, Date value2) {
            addCriterion("birthDate between", value1, value2, "birthdate");
            return (Criteria) this;
        }

        public Criteria andBirthdateNotBetween(Date value1, Date value2) {
            addCriterion("birthDate not between", value1, value2, "birthdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userinfo
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 04 12:29:19 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table userinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}