package com.king.words.dao;

import com.king.words.model.AuthRelation;
import com.king.words.model.AuthRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    long countByExample(AuthRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByExample(AuthRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByPrimaryKey(Integer authrelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insert(AuthRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insertSelective(AuthRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    List<AuthRelation> selectByExample(AuthRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    AuthRelation selectByPrimaryKey(Integer authrelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") AuthRelation record, @Param("example") AuthRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExample(@Param("record") AuthRelation record, @Param("example") AuthRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(AuthRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authrelation
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKey(AuthRelation record);
}