package com.king.words.dao;

import com.king.words.model.AuthInfo;
import com.king.words.model.AuthInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuthInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    long countByExample(AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByExample(AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByPrimaryKey(Integer authid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insert(AuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insertSelective(AuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    List<AuthInfo> selectByExample(AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    AuthInfo selectByPrimaryKey(Integer authid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") AuthInfo record, @Param("example") AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExample(@Param("record") AuthInfo record, @Param("example") AuthInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(AuthInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKey(AuthInfo record);
}