package com.king.words.dao;

import com.king.words.model.DocumentInfo;
import com.king.words.model.DocumentInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DocumentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    long countByExample(DocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByExample(DocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByPrimaryKey(Integer docid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insert(DocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insertSelective(DocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    List<DocumentInfo> selectByExample(DocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    DocumentInfo selectByPrimaryKey(Integer docid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") DocumentInfo record, @Param("example") DocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExample(@Param("record") DocumentInfo record, @Param("example") DocumentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(DocumentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table documentinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKey(DocumentInfo record);
}