package com.king.words.dao;

import com.king.words.model.LoginInfo;
import com.king.words.model.LoginInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    long countByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByPrimaryKey(Integer loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insert(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insertSelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    List<LoginInfo> selectByExample(LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    LoginInfo selectByPrimaryKey(Integer loginid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") LoginInfo record, @Param("example") LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExample(@Param("record") LoginInfo record, @Param("example") LoginInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(LoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table logininfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKey(LoginInfo record);
}