package com.king.words.dao;

import com.king.words.model.RoleRel;
import com.king.words.model.RoleRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    long countByExample(RoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByExample(RoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByPrimaryKey(Integer rolerelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insert(RoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insertSelective(RoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    List<RoleRel> selectByExample(RoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    RoleRel selectByPrimaryKey(Integer rolerelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleRel record, @Param("example") RoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExample(@Param("record") RoleRel record, @Param("example") RoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(RoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rolerel
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKey(RoleRel record);
}