package com.king.words.dao;

import com.king.words.model.WordsInfo;
import com.king.words.model.WordsInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WordsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    long countByExample(WordsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByExample(WordsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int deleteByPrimaryKey(Integer wordsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insert(WordsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int insertSelective(WordsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    List<WordsInfo> selectByExample(WordsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    WordsInfo selectByPrimaryKey(Integer wordsid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") WordsInfo record, @Param("example") WordsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByExample(@Param("record") WordsInfo record, @Param("example") WordsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKeySelective(WordsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wordsinfo
     *
     * @mbg.generated Wed Sep 04 12:29:19 CST 2019
     */
    int updateByPrimaryKey(WordsInfo record);
}